### PR TITLE
Optimize optimisticUI with DB

### PR DESCRIPTION
**Pull request by jamesgibson14**
Okay I am using the NPM Mingo library to do optimiticUI for inserts. I `find` the doc in Mutator and pass the full doc instead of the _id through to the processors. the big changes is in `ObservableCollections.isEligibleByDB`.  I don't know if this is a feasible pull request? 

So far it is working well, it is very much faster because it is not calling mongoDB for each subscription.

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
@jamesgibson14 I really appreciate your PR. 

So... we have isEligible and isEligibleByDB. The reason for the 2nd one is to avoid race-conditions. We could have done this test with LocalCollection package, no need for mingo.

How much faster is it really ? We could have a "race-condition prone" mode that is much faster and lighter on the db.

**Comment by jamesgibson14** [comment]
I have quite a few subscriptions so it is a lot faster, it went from 4000ms to less than 100ms.   each `isEligibleDB` ws about 130ms but since they run synchronously it took the 4000 ms and longer if I had more subs just for one `insert`.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 one insert took 4000ms whaaat ? 

So basically what happened, each processor verified by db the same document. But how many requests were there ? "Quite a few" subscriptions, give me a number please.

Also you could drop mingo and just use isEligible(doc) , does the same thing.
https://github.com/jamesgibson14/redis-oplog/blob/9d6e1765cacc1664ec6cf4a6039e91068d7751fd/lib/cache/ObservableCollection.js#L85

**Comment by jamesgibson14** [comment]
Yes that is what was happening, processor many times. I have like 20 something subscriptions, it is my main channel, I know I could improve that with some more filtered tread to that channel but I haven't been able to update my code yet.

**Comment by jamesgibson14** [comment]
Of those 20+ only 1-2 are usually eligible, but it still queries the db 20+ times.  I recognize that the problem  is mostly with my code: I have a collection with many different types of subscriptions/data, I think I just need to move forward with name-spacing and threads. But

**Comment by theodorDiaconu** [comment]
In the beginning I worked with the same strategy as you, the problem was race conditions. This is why the database is the source of truth. 

I think we should:
1. Allow developer to choose, speed vs race-conditions
2. Have a way to merge db requests for multiple subscriptions, something like:

Phase 1:
- Document change is received
- All processors get notified, and they somehow store somewhere what they need from db to process diffs and they halt processing

Phase 2:
- Database requests get merged and we interogate the db
- We notify processors with the new data, so they can resume

**Comment by jamesgibson14** [comment]
I agree and I don't expect this to be pulled unless we can show that it does work for race conditions.
As far as I know the  latest commit I made, actually treats the DB as the source of truth still.

In Mutator.js it queries not only the _ids but also the fields that changed and then passes that along to the processor and `isEligibleByDB`. It is all done within the same event cycle so it should be okay.
My problem is that I can have dozens of processors per collection name and so it call the db dozens of times, even though it is the same `_id`, My commit calls the db once and passes it on.

Also I just learned about `Minimongo.Matcher`  which replaces `sift` and `mingo`... so one less npm pack needed.  see changes to: lib/cache/ObservableCollection.js

I am still working on it.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 I don't know what to do with this PR. I am now investigating the minimization of db requests when multiple processors are watching.

**Comment by jamesgibson14** [comment]
@theodorDiaconu I think this PR can be closed, but I do think it has some useful code especially in Mutator.js for optimizing db calls, I also added before and after hooks, which also are helpful with optimizing the db calls.
I make `collection.find` with all `fields` in mutator.js right after `update.call`, I believe this solved the race condition as well as not needing to call the db for each subscription... it is only done once, it could also be passed along to the changed functions to save another db call for adding the changed fields because we already have the data.

Why hooks:
The `collection-hooks` package makes a DB call to get the full documents before it runs it's hooks and the redisoplog does the same thing again, with the hooks in this PR I can run the same hooks without calling the DB 2 times for the same data.

**Comment by theodorDiaconu** [comment]
@jamesgibson14 the problem is we are never getting the full document, if hooks wants that, be it, but doing so can be a huge bottleneck, especially for big batch updates.

And even if we get the full document, we are race condition prone:
https://forums.meteor.com/t/meteor-scaling-redis-oplog-status-prod-ready/30855/220?u=diaconutheodor

I thought about allowing this race-condition prone mode, but the problem is that you do unecessary fetches. What if you don't have a listener ?

The only way to solve your problem, as I see it, is when an redis event is received do the following:
1. All processors need to state the fields they need
2. Merge all the fields do a single find
3. Pass the object directly to each processor so it can properly use it.

**Comment by theodorDiaconu** [comment]
https://github.com/cult-of-coders/redis-oplog/issues/182

**Pull request closed without merging**
