### PR TITLE
Use chai by npm and replace chrome by puppeteer

### PR DESCRIPTION
**Pull request by SimonSimCity**
Includes all changes of #316, adds one missing import-statement.

In addition I tried to switch the selenium based chrome test-driver over to puppeteer, which does not require root access or an installation of google chrome.

### CODE REVIEW

**Comment by SimonSimCity** [comment]
Well ... this was a quick change 😄

Can be merged. I feel it wouldn't require a release, but it might be different for @Floriferous ...

**Comment by Floriferous** [comment]
I guess we do need a release for the dependencies to get sorted out properly on our end.

@theodorDiaconu update on this?

**Comment by SimonSimCity** [comment]
Just happened to have the time to fix the conflict.

**Comment by SimonSimCity** [comment]
Any chance this could make it in soon? :)

**Comment by SimonSimCity** [comment]
@theodorDiaconu any news? My application also heavily relies on this package. If you don't have time, I volunteer to help you with managing this package.

**Comment by theodorDiaconu** [comment]
@SimonSimCity will take care today.

**Comment by theodorDiaconu** [comment]
@SimonSimCity thanks for the reminder and sorry it took so long. Released 2.0.5;

**Pull request merged**
