### PR TITLE
Fix tests after updating Mocha

### PR DESCRIPTION
**Pull request by megawebmaster**
Hi! :wave: 

I noticed that people have issues with passing tests. I checked why it happens and it turned out that new versions of Mocha support only one version of tests: either promises (so `async` functions) or regular functions with callbacks (`function(done)`).

Due to what we really test I decided to go with a bit of "callback hell" that can be then improved over time. I didn't have enough time to improve all tests I touched, so I hope it's good enough :wink: 

Everything should pass on Travis now :muscle: 

I hope that you like it and you'll merge it to allow others to contribute to the project in an easier manner.

### CODE REVIEW

**Comment by linegel** [comment]
@theodorDiaconu is there any chance that you could have a look?

**Comment by theodorDiaconu** [comment]
You modified indentation everywhere. Can you fix that pls?

**Comment by megawebmaster** [comment]
@theodorDiaconu - you're right, I accidentally re-formatted file. I'll fix that in my spare time, probably in 2-3 weeks (sorry!)

**Comment by jamesgibson14** [comment]
@megawebmaster I made a pull request to your fork with a fix for indentation.

**Comment by megawebmaster** [comment]
@theodorDiaconu - I forgot about merging changes from @jamesgibson14, sorry about that! The PR should be ready now :muscle:

**Pull request merged**
