### PR TITLE
Include previous doc in dispatched events

### PR DESCRIPTION
**Pull request by elm2178**

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
Why?

**Comment by elm2178** [comment]
@theodorDiaconu it would be great if we could configure this per collection. We are working on some realtime concurrency between a graphql/apollo backend and our meteor server and it would be great if we could optionally publish the previous document for the collections that we specify. This allows us to determine on our apollo server exactly what changed and what next steps to take. Let me know if you want me to clarify our use case further!

**Comment by theodorDiaconu** [comment]
`This allows us to determine on our apollo server exactly what changed and what next steps to take.` This is why we send the modified fields. To determine what changed. Also be careful with data consistency, look in the big redisoplog thread on Meteor to understand why race conditions can occur when sending the doc.

**Comment by elm2178** [comment]
@theodorDiaconu the modified fields aren't sufficient for us. We need to know more than just what fields were modified, we need to know the previous value of those fields so that we can compare them to their current value and determine which users need to receive updates based on that diff. 

I created this PR as an initial test and mainly to begin a discussion around whether or not this would be useful. There are definitely optimizations I can make on this PR:
1. The ability to specify which collections actually need the previous document in their redis messages as part of the redis oplog config. Another approach would be to add this as an update option similar to the 'pushToRedis' bool, we could have a 'includePrevDoc' bool that would default to false and that would allow us to be even more selective about which updates we decide to include the previous document in.
2. Ideally the only fields included would be the fields that were modified on the previous document that way we don't send any 'extra' and unneeded data through.

I know that this might look like additional weight and bloat added to updates done through redis oplog but for our use case it really does seem like it is the most performant solution. I can describe the issue in more depth if you want but on our essentially the issue is that on apollo server we are looking to only publish project updates to users that either currently have access to a project or previously had access to that project. Our project collection has a 'members' field and although redis oplog currently tells us that the 'members' field has changed without maintaining a 'prevDoc' for every active project document subscription for every user there is no way for us to tell if the user previously was a member or not.

When you consider having 30+ servers running and each server needing to maintain a 'prev' doc state for each of the documents that are relevant to that user's subscription, you can see why I considered making this change to redis oplog's redis messages.

**Comment by theodorDiaconu** [comment]
Ok understood, if you make it opt-in, using collection configuration for redis, then it's fine by me :) But it needs to be elegant and properly tested, otherwise I cannot merge it.

**Comment by elm2178** [comment]
@theodorDiaconu okk I think this is much cleaner. Can you review?

**Comment by theodorDiaconu** [comment]
Looks good, I just want a test to make sure it works :)

**Comment by elm2178** [comment]
@theodorDiaconu test added!

**Comment by theodorDiaconu** [comment]
Almost forgot, also add documentation for this. So it's not another feature lost in PRs. Great PR!

**Comment by elm2178** [comment]
@theodorDiaconu documentation added!

**Comment by elm2178** [comment]
@theodorDiaconu bump

**Comment by theodorDiaconu** [comment]
Published 2.0.1

**Comment by theodorDiaconu** [comment]
Thank you @elm2178 for your patience and work, looks great

**Pull request merged**
