### PR TITLE
Release 2.1.0

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Includes PRs #371 and #387. I have also fixed running of tests by migrating them to GH Actions. One test is currently failing @maxpain @megawebmaster can you please take a look.

Also I'm open to get one or two more PRs into this release. Which ones would you like?

### CODE REVIEW

**Comment by maxpain** [comment]
@StorytellerCZ, Where I can see error logs of tests in GitHub Actions?

**Comment by StorytellerCZ** [comment]
You will need to go to the origin repository: https://github.com/Meteor-Community-Packages/redis-oplog/actions

**Comment by maxpain** [comment]
Hmmm, this is strange error, because we don't call collection2 `attachSchema` method on `Meteor.users` anywhere.
Maybe some third-party package does it?

```
Exception while invoking method 'accounts_createUser' Error: After filtering out keys not in the schema, your modifier is now empty
    at doValidate (packages/aldeed:collection2/collection2.js:431:11)
    at hook.Mongo.Collection.<computed> [as update] (packages/aldeed:collection2/collection2.js:199:14)
    at hook.update (packages/cultofcoders:redis-oplog/lib/mongo/Mutator.js:171:45)
    at hook.update (packages/cultofcoders:redis-oplog/lib/mongo/extendMongoCollection.js:40:35)
    at MethodInvocation.accounts_createUser (packages/local-test:cultofcoders:redis-oplog/testing/accounts/server.js:63:22)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1885:12)
    at packages/ddp-server/livedata_server.js:769:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:767:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1257:12)
    at packages/ddp-server/livedata_server.js:765:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:739:23)
    at packages/ddp-server/livedata_server.js:603:43
```

**Comment by StorytellerCZ** [comment]
That should not be the case, but looks like we will have to make a review of them to fix this.

**Comment by edemaine** [comment]
The error message says it happens in the `aldeed:collection2` package. Presumably a test of compatibility with that package?

**Comment by StorytellerCZ** [comment]
No, that is just collection2 reporting that after it has filtered out stuff that was not in the schema, there was nothing left. collection2 is just the reporter here.

**Comment by maxpain** [comment]
But we didn't attach `collection2` to `Meteor.users` collection.

**Comment by StorytellerCZ** [comment]
To be more precise we did not attach a schema. We need to find where `collection2` is getting added in the dependencies or somewhere. I'll try to take a look soonish. If not this week, then definitelly next.

**Comment by donstephan** [comment]
This is from the `socialize:user-model` package which is attaching the user model. You can see [here](https://github.com/copleykj/socialize-user-model/blob/devel/common/user-model.js) it doesn't support `roles` or `something` which is causing the user update to fail. I assume we can extend that `User` model in there or just remove it completely since it's really not necessary for these tests. I'll take a look at this this week.

**Comment by edemaine** [comment]
> Also I'm open to get one or two more PRs into this release. Which ones would you like?

#363 might be worth looking at, though I don't personally need it; what I'd personally like in this space is a nicer solution to #357. (My biggest issue remains #365 though; I still don't have a fix other than restarting my Meteor processes every week or so.)

**Comment by donstephan** [comment]
Running with vent only mode would definitely be useful to some. Probably a big of rework around the tests (or just rerun a subset of tests with this configuration option turned on). I also don't think it effectively solves #365. Correct me if I'm wrong but I do believe the goal with this release need to be support for 2.6+ before adding additional features.

**Comment by donstephan** [comment]
Just a heads up PR [here](https://github.com/Meteor-Community-Packages/redis-oplog/pull/1) that fixes this.

**Comment by StorytellerCZ** [comment]
Published cultofcoders:redis-oplog@2.1.0

**Comment by heberallred** [comment]
@edemaine I posted a code tweak that may help.  We had the same issue, and decided that a little extra DB load is justified to keep the server cache in sync.  This may not be the case for some applications, but it works well for us so far.
[https://github.com/zzbots/redis-oplog/commit/d4a8c40379319bf05c6b5593b5718b9216958373](https://github.com/zzbots/redis-oplog/commit/d4a8c40379319bf05c6b5593b5718b9216958373)

Here are some additional comments/context: [https://github.com/cult-of-coders/redis-oplog/issues/291#issuecomment-1271720613](https://github.com/cult-of-coders/redis-oplog/issues/291#issuecomment-1271720613)

**Pull request merged**
