### PR TITLE
fix client side updates

### LINKED ISSUE #38: Client-side updates are not pushed to Redis.
Calls to insert, update and remove methods on client-side collections doesn't seem to be published reactively...

As good practise, we've been wrapping the calls to client-side collection methods in Meteor methods for some time now. I guess (still not tested it) in those cases everything would work fine because the collection method would eventually be called during the server-side execution of the Meteor method (I wish they would have found another name for that, so confusing).

But we have a very big and old codebase and we still have a lot of calls to client-side collection methods directly in inappropriate places like template event handlers (sorry I feel sick just saying that, I hope your ears are not bleeding) and refactoring the whole thing is not necessarily realistic at this point...

@theodorDiaconu Any thoughts on that?

### PR DESCRIPTION
**Pull request by maxnowack**
Extend the prototype of the collection driver instead of just the collection prototype.
Resolves #38

### CODE REVIEW

**Comment by maxnowack** [comment]
The tests are failing. This is because you've changed the default argument order (..., config, callback) to ..., callback, config.
But changing this back to default would be a breaking change that I want to discuss.

**Comment by maxnowack** [comment]
@theodorDiaconu, it turned out that it is not as easily switching the `_config` and `cb` parameter. The original insert and remove method will not pass the config down to the corresponding driver method.

In my opinion, the best way so far would be to define a function which gets called to return the config. This function could be configured with a custom callback:
````es6
const Posts = new Mongo.Collection('posts')
Posts.getRedisConfig((type, ...args) => {
  // config based on type
  if (type === 'insert') {
    return { namespace: 'x' }
  } else {
    return { pushToRedis: false }
  }

  // or do something with the args. args are the arguments,
  // that were originally passed to the driver method
  // insert(doc)
  // update(selector, modifier, config)
  // remove(selector)
})

// an object can also be passed to getRedisConfig
Posts.getRedisConfig({
  insert(doc) {
      // ...
  },
  update(selector, modifier, config) {
      // ...
  },
  remove(selector) {
      // ...
  },
})
````

what do you think?

**Comment by maxnowack** [comment]
I've implemented it as proposed. I think it's easier to discuss some code :)

**Comment by theodorDiaconu** [comment]
So let me understand, if I want to insert into a custom channel from some part of the app. I would have to modify getRedisOptions() ? 

The thing is, doing this just to support client-side inserts (which are no longer recommended) makes me feel a bit unsure. What do you think ?

**Comment by maxnowack** [comment]
Yes, the idea was to have a configuration function, which decides on the passed arguments, which option will be used. While this makes sense for custom channels (relying on a property of the document), it doesn't make sense at all with the `publishToRedis` option. `publishToRedis` will probably be used in combination with costly or high frequently method calls, which cannot be calculated based on the passed arguments.

As you mentioned, client side operations are not recommended and in my opinion the costs for supporting this is too high. Another workaround could it be to completely turn of the automatic registration of the mutation methods and define new ones which are using the same api but are compatible with redis oplog.

I think we can close this PR for now.

**Comment by theodorDiaconu** [comment]
@maxnowack the thing is... there may be a super easy way. Maybe something like
```
Collection.context({channel: 'xxx'}).insert() ?
```

That may be a better API ?

**Comment by maxnowack** [comment]
but how do you get the context inside the overridden `Collection._collection.insert`?

**Comment by theodorDiaconu** [comment]
@maxnowack yes you are right.. very sorry your effort was not merged (it is very appreciated), but we realized that we should not support this. At least until we find a easy solution.

**Comment by maxnowack** [comment]
@theodorDiaconu we still have some client side mutations in our app, so I have to find a solution or at least a workaround for this :)

**Pull request closed without merging**
