### PR TITLE
Fix monkey-patching of the Mongo.Collection class

### PR DESCRIPTION
**Pull request by SimonSimCity**
Fixes https://github.com/cult-of-coders/redis-oplog/issues/304 ~by replacing the map of collections by the usage of `dburles:mongo-collection-instances` which internally does the correct monkey-patching of the constructor of `Mongo.Collection` based on https://github.com/rclai/meteor-collection-extensions.~ Replaced by a different approach, see the following comments later.

### CODE REVIEW

**Comment by SimonSimCity** [comment]
`StubCollections` as created by https://github.com/hwillson/meteor-stub-collections do not work with this PR ...

**Comment by SimonSimCity** [comment]
Just saw that you ditched the package `dburles:mongo-collection-instances ` in https://github.com/cult-of-coders/redis-oplog/commit/6ee3c03119778e9ceff7e4c26039a954c5ee14f0#diff-3cf62802c189329be537bd8f2387c5fe because of the packages weak dependency on `account-base` ...

Because I don't know when https://github.com/hwillson/meteor-stub-collections/issues/32 will be merged, I'll just hand over the changes in here.

**Comment by SimonSimCity** [comment]
I've reviewed https://github.com/hayk94/redisOplogIssue and it covers the problem faced there as well.

**Comment by jorgeer** [comment]
I've also encountered issues with the "users" collection not being found, this might fix that problem as well?

**Pull request merged**
