### PR TITLE
Fix bug for when field projector is an empty {}

### PR DESCRIPTION
**Pull request by jamesgibson14**

### CODE REVIEW

**Comment by theodorDiaconu** [comment]
@jamesgibson14 if, fields: {} is empty, then it means it's only _id: 1, right ?

**Comment by jamesgibson14** [comment]
No, minimongo and Mongodb both treat an empty projector object as all fields. 
`Records.find({_id: 'abc'}, {fields:{}})` returns the full document.

**Comment by theodorDiaconu** [comment]
But it is very confusing what I would do, is top level in ObservableCollection if (options.fields is empty) delete it.

**Comment by jamesgibson14** [comment]
My patch works just fine as far as I know, I guess deleting it would work too.

**Comment by theodorDiaconu** [comment]
Patch is indented with 2, the rest of the code is with 4. And also it breaks the logic in the function name "filterAllowedFields", if the array is empty it allows all fields, which is bad, this is why it's best if we put it on the ObservableCollection top level, to delete fields from options if empty

**Comment by jamesgibson14** [comment]
On Tue, Jan 17, 2017 at 3:54 AM, Theodor Diaconu <notifications@github.com>
wrote:

> if the array is empty it allows all fields, which is bad, this is why it's
> best if we put it on the ObservableCollection top level, to delete fields
> from options if empty


Okay that sounds fine, would you like me to submit a new pull request?

**Comment by theodorDiaconu** [comment]
Yes, that would be great!

**Pull request closed without merging**
