### PR TITLE
Fix SyntheticMutator isArray bug

### PR DESCRIPTION
**Pull request by jamesgibson14**
This was reported in #286, I ran into the same issue and was able to fix it.

### CODE REVIEW

**Comment by jamesgibson14** [comment]
@theodorDiaconu this is a bug fix, can it get merged... I am not sure why the tests are not passing, it doesn't have to do with the PR changes.

**Comment by theodorDiaconu** [comment]
We have to solve the tests as well. This might be to the new updates done to minimongo ?
```

     Error: Resolution method is overspecified. Specify a callback *or* return a Promise; not both.
      at http://localhost:3000/packages/meteortesting_mocha-core.js?hash=7f194b23124422b61a3b77e131b48479866d89e3:15122:11
      at Object.changed (packages/local-test_cultofcoders_redis-oplog.js?hash=080e55c2d5e497e57226d5bd018cc2a08c9ae806:1863:11)
      at http://localhost:3000/packages/minimongo.js?hash=bb17400235469027310b81f0d525d28875f12863:1718:14
```

**Comment by megawebmaster** [comment]
This PR will pass tests after merging fixes to tests from #371

**Comment by StorytellerCZ** [comment]
Closing this as this has been superseded by https://github.com/Meteor-Community-Packages/redis-oplog/pull/2

**Pull request closed without merging**
